server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: gwam
    password: 12345
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 215762037130-r4g34crk38mq7iq0ck6ak8gi0sau5979.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 358509953057852
            client-secret: 4e396a694adba01d9baf2e501f644021
            scope:
              - email
              - public_profile


